### PR TITLE
docs: update docs for pod security

### PR DESCRIPTION
**Pull request by paucampana**
add new section to see how to disable admission control in control plane

Signed-off-by: Pau Campana <pau.campanya.soler@gmail.com>

# Pull Request

Add a section for how admission control can be disabled in the control plane

## Why? (reasoning)

It is not clear how it could be disabled.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by smira — COMMENTED** [review]
I'm torn on whether we keep it documented here. I don't want to give a bad advice.

Other people might have different ideas, I thought about having it in a Knowledge Base?

But I would really like people to tag namespaces with different policies if they need to vs. disabling it altogether.

**Comment by frezbo** [comment]
> But I would really like people to tag namespaces with different policies if they need to vs. disabling it altogether.

Agree on this, this default policies prevent a lot of mis-configurations or potential privilege escalations. It easy to add exceptions while keeping the policy enabled.

**Comment by frezbo** [comment]
> In our case for example, we are using [gatekeeper](https://github.com/open-policy-agent/gatekeeper).

that's a valid use case, let's get this moved over to the knowledgebase then

**Comment by paucampana** [comment]
> > In our case for example, we are using [gatekeeper](https://github.com/open-policy-agent/gatekeeper).
> 
> that's a valid use case, let's get this moved over to the knowledgebase then

Added in knowledge base section

**Review by smira — APPROVED** [review]
thank you!

**Pull request merged**
