### PR TITLE
docs: fix broken link to powershell module

### PR DESCRIPTION
**Pull request by tech1ndex**
- Small update to documentation, basically looks like the maintainer of another [referenced project](https://github.com/nebula-it/New-TalosVM) changed their folder structure, thus resulting in a broken link in your documentation.

- Just trying to provide a better documentation experience to the lowly Windows users out there 😄

- Very small change, love the project and your docs to just happy to keep them clean.

Re-submitted with conventional commit.

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
Thank you :heart:

**Comment by tech1ndex** [comment]
@frezbo No problem! btw any Talos t-shirts or stickers kicking around? 😏

**Comment by frezbo** [comment]
> @frezbo No problem! btw any Talos t-shirts or stickers kicking around? smirk

could you reach out to @rsmitty on slack>

**Pull request merged**
