### PR TITLE
backports: for v1.3.5

### PR DESCRIPTION
**Pull request by smira**
PRs backported:

- #6837 
- #6838 
- #6840 
- #6843 
- #6857

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Comment by frezbo** [comment]
also pkgs update for containerd/kernel

**Comment by smira** [comment]
> also pkgs update for containerd/kernel

yes, but you already did that :heart:

**Comment by frezbo** [comment]
containerd is still on 1.6.16, .18 had some cve fixes https://github.com/siderolabs/pkgs/commit/ee0d97bb26ed22623e69b570e9998e91d2989080

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
> containerd is still on 1.6.16, .18 had some cve fixes [siderolabs/pkgs@ee0d97b](https://github.com/siderolabs/pkgs/commit/ee0d97bb26ed22623e69b570e9998e91d2989080)

yep, thanks, `go-vulncheck` stopped me :)

**Pull request merged**
