### PR TITLE
add Vandebron to adopters list

### PR DESCRIPTION
**Pull request by timvandruenen**
# Pull Request

## What? (description)
Adds Vandebron to the ADOPTERS.md

## Why? (reasoning)
Because its true.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by smira** [comment]
@timvandruenen can you please add DCO to your commit? 

`git commit --amend -s` (sign-off) if you're using CLI

**Comment by timvandruenen** [comment]
I signed off my commits and forced a git push, but the dco check still seems to fail?

**Comment by smira** [comment]
> I signed off my commits and forced a git push, but the dco check still seems to fail?

that's probably because of the merge commit, I can fix it up

**Review by smira — APPROVED** [review]
thank you!

**Pull request merged**
