### PR TITLE
feat: update etcd to 3.5.3

### PR DESCRIPTION
**Pull request by smira**
See https://github.com/etcd-io/etcd/releases/tag/v3.5.3

This release should contain a fix for data consistency issue when etcd
is killed under high load.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5344)

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
do we need to disable the check we added earlier, i think i saw it's default now (have to confirm)

**Comment by smira** [comment]
> do we need to disable the check we added earlier, i think i saw it's default now (have to confirm)

I believe it's  not default in 3.5, but I might be wrong

**Comment by frezbo** [comment]
> > do we need to disable the check we added earlier, i think i saw it's default now (have to confirm)
> 
> I believe it's not default in 3.5, but I might be wrong

Should we set this `experimental-corrupt-check-time` too https://github.com/etcd-io/etcd/issues/9190#issue-290574193=

**Comment by smira** [comment]
> Should we set this `experimental-corrupt-check-time` too [etcd-io/etcd#9190 (comment)](https://github.com/etcd-io/etcd/issues/9190#issue-290574193)

I'm concerned with the performance implications of that, and etcd maintainers say it's significant for big deployments.

**Pull request merged**
