### PR TITLE
docs: add banner to main page

### PR DESCRIPTION
**Pull request by rsmitty**
This PR adds a banner to the splash to make it look a bit nicer.

Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5254)

### CODE REVIEW

**Comment by frezbo** [comment]
seems `website/content/featured-background.png` is not used

**Review by frezbo — APPROVED** [review]

**Comment by rsmitty** [comment]
deploy preview here https://624484a7f71630000a130cba--talos-dev.netlify.app/

**Review by smira — APPROVED** [review]
:heart:

**Pull request merged**
