### PR TITLE
chore: update project in GCP testing

### PR DESCRIPTION
**Pull request by rsmitty**
This PR moves the GCP tests to a new project there. I'm working on consolidating projects, names, and doing some reservations out there.

### CODE REVIEW

**Comment by rsmitty** [comment]
This will need a backport to the 1.7 release branch as well. Will chase this PR with that.

**Comment by frezbo** [comment]
I really want to use TF for gcp too, since all others have moved to using TF

**Comment by rsmitty** [comment]
@frezbo sure, agree with that soon. filed https://github.com/siderolabs/talos/issues/8740 so we can plan that.

**Review by andrewrynhard — APPROVED** [review]

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
