### PR TITLE
release(v1.0.0): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v1.0.0 release.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5239)

### CODE REVIEW

**Comment by frezbo** [comment]
do we need the files from `_gen`?

**Review by frezbo — APPROVED** [review]

**Review by rsmitty — APPROVED** [review]

**Pull request merged**
