### PR TITLE
chore: update kernel and other packages

### PR DESCRIPTION
**Pull request by dsseng**
# Pull Request

## What? (description)
Kernel updates enable SELinux, intel_idle and update kernel version

## Why? (reasoning)
Starting working on SELinux support, apply updates

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by smira — APPROVED** [review]
I don't know if there was a kernel version bump through these updates, but if there was, you need to update kernel version in machinery/constants

**Comment by dsseng** [comment]
It has been bumped to 6.6.28, yes

image

**Comment by dsseng** [comment]
Updated

**Pull request merged**
