### PR TITLE
backports: for v1.4.2

### PR DESCRIPTION
**Pull request by smira**
PRs backported:

* Linux 6.1.27, containerd 1.6.21, runc 1.1.7, go 1.20.4
* #7156 
* #7168 
* #7172 
* #7176 
* #7178 
* #7182 
* #7175 
* #7186

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Comment by frezbo** [comment]
we should also remove `buildid` right?

**Comment by smira** [comment]
> we should also remove `buildid` right?

I'll test that separately in `main` and remove it.

**Pull request merged**
