### PR TITLE
feat: link support matrix in k8s update doc

### PR DESCRIPTION
**Pull request by alexpdp7**
# Pull Request

## What? (description)

Add a link to the support matrix page in the upgrading Kubernetes guide.

## Why? (reasoning)

I was working on my Talos update procedure, and it wasn't immediately obvious to me how I should upgrade K8S. I [opened a discussion to ask](https://github.com/siderolabs/talos/discussions/7242#discussioncomment-5942386). I think this small change will make it easier for others.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by alexpdp7** [comment]
I did not run `make docs`, but I did run `make docs-preview`[^1]. Also I wasn't sure if I should add the change to other versions of the documentation.

[^1]: Although I had to add `--security-opt label=disable` to the Docker command so it would work under Podman.

**Review by smira — APPROVED** [review]
thank you!

**Pull request merged**
