### PR TITLE
Hyperlink to Docker docs on `config.json`

### PR DESCRIPTION
**Pull request by sanmai-NL**
# Pull Request

## What? (description)

Hyperlink to Docker docs on `config.json`. 

## Why? (reasoning)

Reduce time needed to navigate docs.

## Acceptance

Please use the following checklist:

- [ ] you generated documentation (`make docs`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by smira — CHANGES_REQUESTED** [review]
this file is automatically generated from `v1alpha_types.go`, so it doesn't make sense to change this, but rather change the Go file and run `make docs`

**Comment by sanmai-NL** [comment]
> this file is automatically generated from `v1alpha_types.go`, so it doesn't make sense to change this, but rather change the Go file and run `make docs`

I'm now doing that.

It's curious how resource intensive building the docs is though.

**Comment by sanmai-NL** [comment]
@smira I have spent quite some time getting the `make docs` build working. I use MacOS and `nerdctl` or `podman` and neither works due to the build's dependence on some Docker Engine features and/or a defect in `nerdctl`. I very much prefer not to install Docker Engine/Desktop for this. Is there some cloud environment (Codespace, etc.) where I can develop for Talos Linux? If not, can you run `make docs` yourself and push the result to this PR branch, please?

**Comment by smira** [comment]
> @smira I have spent quite some time getting the `make docs` build working. I use MacOS and `nerdctl` or `podman` and neither works due to the build's dependence on some Docker Engine features and/or a defect in `nerdctl`. I very much prefer not to install Docker Engine/Desktop for this. Is there some cloud environment (Codespace, etc.) where I can develop for Talos Linux? If not, can you run `make docs` yourself and push the result to this PR branch, please?

sure, thanks, I will clean it up

**Review by smira — APPROVED** [review]

**Pull request merged**
