### PR TITLE
feat: add `.der` output `talosctl gen secureboot pcr`

### PR DESCRIPTION
**Pull request by utkuozdemir**
Output the PCR public key in `.der` format in addition to the `.pem` format.

Closes siderolabs/talos#7742.

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Comment by frezbo** [comment]
I can't recollect the original intention of the issue whether we needed the certs or db files in der format. Anyways this should be good for now

**Comment by utkuozdemir** [comment]
@frezbo do you see anything that is missing?

**Comment by frezbo** [comment]
> @frezbo do you see anything that is missing?

all good, since I can't recollect :sweat_smile:

**Comment by utkuozdemir** [comment]
> > @frezbo do you see anything that is missing?
> 
> all good, since I can't recollect 😅

alright then 😆

**Pull request merged**
