### PR TITLE
feat: implement tracking of blockdevice secondaries

### PR DESCRIPTION
**Pull request by smira**
This is going to be used to detect disks that are safe to wipe.

For blockdevices, track secondaries as direct references, e.g. encrypted `STATE` partition might have secondary `vda5`.

For disks, re-map secondaries to be whole devices names, e.g. `vda`.

### CODE REVIEW

**Comment by frezbo** [comment]
need tests?

**Comment by smira** [comment]
> need tests?

yes... good idea, I will do

**Comment by smira** [comment]
> > need tests?
> 
> yes... good idea, I will do

added some tests for secondary disks detection

**Review by frezbo — APPROVED** [review]

**Pull request merged**
