### PR TITLE
docs: default to brew docs for talosctl

### PR DESCRIPTION
**Pull request by rothgar**
Updated all install instructions and added install page for future OS specific install instructions

# Pull Request

## What? (description)
Updates default install instructions for talosctl to use `brew`
## Why? (reasoning)
We want people to have an easier way to keep talosctl updated
## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]

**Comment by rothgar** [comment]
I didn't know there was a markdown lint step that required 1 sentence per line. Fixed and force pushed.

I really like that markdown format and this is the first project I've worked on that enforced it :+1:

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
@rothgar please copy your changes to website/v1.8 docs, as the latest (pre-release) docs are the template for the future docs, otherwise we'd lose your changes

**Comment by rothgar** [comment]
Added 1.8 in #8795

**Pull request merged**
