### PR TITLE
chore: add tests for chelsio drivers

### PR DESCRIPTION
**Pull request by frezbo**
Add tests for Chelsio drivers and firmware.

Ref: https://github.com/siderolabs/extensions/pull/232

### CODE REVIEW

**Review by smira — APPROVED** [review]
promote it?

**Comment by frezbo** [comment]
> promote it?

well it's broken :sweat_smile: , since it uses old code to install extensions

**Comment by frezbo** [comment]
i tested locally

**Comment by smira** [comment]
> > promote it?
> 
> well it's broken 😅 , since it uses old code to install extensions

ah... yes... I need to get a fix in... my bad

**Pull request merged**
