### PR TITLE
fix: add a link-scope route if the cmdline gateway is not reachable

### LINKED ISSUE #7020: Talos does not boot correctly in /32 subnets
### Description

I'm using a Hetzner server with Proxmox installed in routed mode as described [here](https://community.hetzner.com/tutorials/install-and-configure-proxmox_ve#example-of-the-guest-configuration-in-routed-setup)

To install Talos, the [documentation](https://www.talos.dev/v1.3/talos-guides/install/virtualized-platforms/proxmox/) describes the `ip=` kernel parameter, that I set according to the screenshot:

image

For the sake of privacy, I removed the IP addresses. Let's take 192.168.0.2 as the IP address of the gateway and 10.0.0.42 as the IP address of the Talos VM.

After booting, the system does not come up and isn't responding to ping. In tcpdump I can only see ARP requests coming from the vm host.

### Logs

talos_logs

### Environment

- Talos version: 1.3.6
- Kubernetes version: none, pre-install environment
- Platform: Hetzner/Proxmox

### PR DESCRIPTION
**Pull request by smira**
Fixes #7020

### CODE REVIEW

**Comment by frezbo** [comment]
needs backport?

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
> needs backport?

I feel it's a change we shouldn't backport... but I'm torn, idk

**Comment by sergelogvinov** [comment]
I've had the same case. And I solve it by using IPv6... 
thank you for `link-scope route` ❤️

**Pull request merged**
