### PR TITLE
chore: update Go to 1.19.5, kernel to 6.1.4

### PR DESCRIPTION
**Pull request by DmitriyMV**
Release notes https://go.dev/doc/devel/release#go1.19.5

Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>

### CODE REVIEW

**Review by smira — COMMENTED** [review]
make generate, and also kernel version changed to 6.1.4 in pkgs

**Review by Unix4ever — APPROVED** [review]

**Review by smira — COMMENTED** [review]
and also update `hack/release.toml`

**Comment by DmitriyMV** [comment]
@smira 
> make generate, and also kernel version changed to 6.1.4 in pkgs

> and also update `hack/release.toml`

Done.

**Review by smira — APPROVED** [review]

**Pull request merged**
