### PR TITLE
docs: add component diagram about K8s & Talos Linux

### PR DESCRIPTION
**Pull request by sanmai-NL**
# Pull Request

## What? (description)

See title.

## Why? (reasoning)

In the current docs, many different, tools, services, i.e. components are mentioned in writing. Just the text makes the overall picture unclear.

## Acceptance

Please use the following checklist:

- [ ] ~you linked an issue (if applicable)~
- [ ] ~you included tests (if applicable)~
- [x] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [ ] ~you ran unit-tests (`make unit-tests`)~

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by sanmai-NL** [comment]
Why does the bot report the commit body as empty?

**Comment by smira** [comment]
@sanmai-NL thanks for the diagram, do you have source file available for it so that it could be updated in the future?

**Comment by smira** [comment]
> Why does the bot report the commit body as empty?

the commit body is really empty :) Signed-off line doesn't count, just a sentence will be great

**Comment by sanmai-NL** [comment]
> > Why does the bot report the commit body as empty?
> 
> 
> 
> the commit body is really empty :) Signed-off line doesn't count, just a sentence will be great

Ah, you mean the commit message body text.

**Comment by sanmai-NL** [comment]
> @sanmai-NL thanks for the diagram, do you have source file available for it so that it could be updated in the future?

Yeah, where to add it?

**Comment by frezbo** [comment]
> > @sanmai-NL thanks for the diagram, do you have source file available for it so that it could be updated in the future?
> 
> Yeah, where to add it?

i think the same path is fine `website/static`

**Comment by sanmai-NL** [comment]
@frezbo @smira: ready for review. Don't know about the number of commits ahead failure, I manually rebased against the default branch, and again when I saw this failure. But then the default branch moved ahead and I used the GitHub update-to-main based on a merge commit.

**Review by frezbo — APPROVED** [review]

**Pull request merged**
