### PR TITLE
feat: support vlan/bond in v1, vlan in v2 for nocloud

### LINKED ISSUE #9753: nocloud network support vlans and bonds
## Feature Request

`nocloud` Talos should add support for vlans and bonds for v1 metadata, and vlans for v2 metadata. 

### Description

In the `nocloud` platform code we don't parse the bond or vlan type for `version: 1`:
https://github.com/siderolabs/talos/blob/main/internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go#L300

And vlans aren't parsed for `version: 2` metadata:
https://github.com/siderolabs/talos/blob/main/internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go#L598

### LINKED ISSUE #9871: nocloud do not wait for known physical network interfaces to be up before configuring network
`nocloud` variant doesn't wait for all known to it (listed in config ethernets) to be up in State before configuring network. this cause server to be left in unreachable state.

### Logs

[talos-log.txt](https://github.com/user-attachments/files/17996297/talos-log.txt)

### Environment

- Talos version: 1.8.3
- Platform: nocloud

### PR DESCRIPTION
**Pull request by smira**
Fixes #9753

Fixes #9871

### CODE REVIEW

**Review by TimJones — APPROVED** [review]

**Comment by smira** [comment]
Waiting for the change to be tested on PNAP (@rsmitty)

**Comment by smira** [comment]
I pushed more changes from #9871

**Comment by smira** [comment]
PNAP testing :heavy_check_mark:

**Comment by smira** [comment]
servers.com testing :heavy_check_mark:

**Pull request merged**
