### PR TITLE
chore: add ice drivers

### PR DESCRIPTION
**Pull request by frezbo**
Add Intel ice drivers and bump kernel to 5.15.68

Signed-off-by: Noel Georgi <git@frezbo.dev>

### CODE REVIEW

**Review by smira — APPROVED** [review]
do we need to do same firmware on arm64?

bump of kernel version in constants.go is missing... and probably hack/release.toml (but I have it in my PR, I can probably fix it up there)

**Comment by frezbo** [comment]
> do we need to do same firmware on arm64?

I'm not sure, i'll add it just in case.

**Comment by frezbo** [comment]
> > do we need to do same firmware on arm64?
> 
> I'm not sure, i'll add it just in case.

This increases the initramfs size by 632KB when uncompressed.

**Comment by smira** [comment]
> > > do we need to do same firmware on arm64?
> > 
> > 
> > I'm not sure, i'll add it just in case.
> 
> This increases the initramfs size by 632KB when uncompressed.

I would go this way for the sake of consistency... There might be arm64 servers with ICE? on other hand it's pretty rare

**Review by smira — APPROVED** [review]

**Pull request merged**
