### PR TITLE
fix: correct link to api access from k8s

### PR DESCRIPTION
**Pull request by ammmze**
# Pull Request

## What? (description)

Correct link to the Talos API access from Kubernetes.

## Why? (reasoning)

The previous link went to a non-existent page.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by ammmze** [comment]
Looking at the conform.yaml and the conform policy code, it looks like that `conform/commit/gpg-identity` is expected to fail unless I am a member of the `siderolabs` Organization? So I guess that presumably means I'll need one you folks to co-author my commit?

**Review by frezbo — APPROVED** [review]

**Comment by frezbo** [comment]
> Looking at the conform.yaml and the conform policy code, it looks like that `conform/commit/gpg-identity` is expected to fail unless I am a member of the `siderolabs` Organization? So I guess that presumably means I'll need one you folks to co-author my commit?

yes, we require all commits to be signed by one of our devs, so we do re-signing and push to HEAD for all community PR's

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
