### PR TITLE
feat: update Kubernetes to 1.30.0

### PR DESCRIPTION
**Pull request by smira**
See https://github.com/kubernetes/kubernetes/releases/tag/v1.30.0

### CODE REVIEW

**Comment by frezbo** [comment]
to main?

**Comment by smira** [comment]
> to main?

yes, I think we did two PRs at the same time

**Comment by frezbo** [comment]
> > to main?
> 
> yes, I think we did two PRs at the same time

I'll close mine then, also missing update here: website/content/v1.7/_index.md

**Comment by smira** [comment]
> > > to main?
> > 
> > 
> > yes, I think we did two PRs at the same time
> 
> I'll close mine then, also missing update here: website/content/v1.7/_index.md

that's on purpose, I have #8586 going

**Review by utkuozdemir — APPROVED** [review]

**Review by TimJones — APPROVED** [review]

**Pull request merged**
