### PR TITLE
docs: kubeProxyReplacement from "disabled" to "false"

### PR DESCRIPTION
**Pull request by a-mader**
# Pull Request

## What? 
Fix incorrect helm install command for cilium

## Why? 
User have a better experience installing cilium

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by smira — APPROVED** [review]
thank you

**Review by frezbo — COMMENTED** [review]
note to self, check if we are using same values in our ci, i think I updated there, but not docs

**Review by frezbo — APPROVED** [review]

**Comment by frezbo** [comment]
> note to self, check if we are using same values in our ci, i think I updated there, but not docs

This is already done

**Pull request merged**
