### PR TITLE
feat: update Kubernetes to 1.28.0

### PR DESCRIPTION
**Pull request by smira**
See https://github.com/kubernetes/kubernetes/releases/tag/v1.28.0

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
let's run the qemu csi integration test too

**Comment by smira** [comment]
this wasn't ready quite yet... but not a big deal

**Comment by frezbo** [comment]
> this wasn't ready quite yet... but not a big deal

sorry, I realized that late, I thought I could rebase my integration test PR on this and move on to other work, but unfortunately, it still fails :sweat:

**Pull request merged**
