### PR TITLE
release(v1.2.3): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v1.2.3 release.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Comment by smira** [comment]
I can re-do the release

**Comment by frezbo** [comment]
> > should i get in the .69 kernel?
> 
> anything fun there?

I haven't finished checking yet :sweat:

**Review by frezbo — APPROVED** [review]

**Pull request merged**
