### PR TITLE
docs: update index page

### PR DESCRIPTION
**Pull request by andrewrynhard**
Simplify the index page.

Signed-off-by: Andrew Rynhard <andrew@rynhard.io>

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5201)

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
@rsmitty can you please update with your nice block you had in one of the iterations?

**Comment by rsmitty** [comment]
Yep, happy to do that but it's gonna take a bit of work. The styling for that was based on a different theme and I'll need to port some things over. Let's get this one merged in the meantime and then chase it.

**Comment by smira** [comment]
looks like `conform` is confused on checking out this PR. I will re-create it under new PR

**Comment by smira** [comment]
re-created as #5241

**Pull request closed without merging**
