### PR TITLE
chore: allow custom pkgs to build talos

### PR DESCRIPTION
**Pull request by si0ls**
# Pull Request

## What? (description)

Use provided pkgs inside Dockerfile to allow build with custom pkgs from any registry

## Why? (reasoning)

Following on from #8164, impossible to `make imager` or `make installer` with specific u-boot build
It would be nice to be able to customise all of the components so that we could more easily test, fork and contribute to certain packages while remaining based on Talos releases for unaffected elements.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by smira — COMMENTED** [review]
thanks, this makes sense, but it won't work without new args added to `COMMON_ARGS`

also you commit misses a DCO (you need to sign-off on your commits)

**Comment by si0ls** [comment]
> thanks, this makes sense, but it won't work without new args added to `COMMON_ARGS`
> 
> also you commit misses a DCO (you need to sign-off on your commits)

I don't know how I forgot to add args to `COMMON_ARGS`

Thanks for the review 
I'll try to update tomorrow

**Comment by si0ls** [comment]
@smira I added the args to COMMON_ARGS and signed my commits (had to force push)
I think it's ok for second review and maybe merge 😉

**Review by Unix4ever — APPROVED** [review]

**Review by frezbo — APPROVED** [review]

**Pull request merged**
