### PR TITLE
fix: update field name for bus path disk selector

### PR DESCRIPTION
**Pull request by smira**
`s/buspath/bus_path/`.

### CODE REVIEW

**Review by utkuozdemir — APPROVED** [review]

**Review by frezbo — APPROVED** [review]

**Review by Unix4ever — APPROVED** [review]

**Comment by ammmze** [comment]
Does this happen to fix this error I receive when doing a `talosctl validate` on a config that contains an install disk `busPath`?

```
2 errors occurred:
        * install disk selector is invalid: ERROR: <input>:-1:0: undefined field 'buspath'
        * either install disk or diskSelector should be defined
```

**Comment by twelho** [comment]
Most likely encountering this in https://github.com/siderolabs/talos/issues/10080 while trying to upgrade to v1.9, nice to see it's proposed for backporting.

**Comment by budimanjojo** [comment]
Seems like this commit is not inside v1.10.0-alpha.0 version. Is there any plan to release a new alpha or can this be backported to v1.10.0.alpha.0? Thank you!

**Comment by frezbo** [comment]
> Seems like this commit is not inside v1.10.0-alpha.0 version. Is there any plan to release a new alpha or can this be backported to v1.10.0.alpha.0? Thank you!

you can use thetalos from main

alpha.2 is scheduled for Feb 2025, https://github.com/siderolabs/talos/issues/10160

**Pull request merged**
