### PR TITLE
docs: add example of forwarding talos logs to vector

### PR DESCRIPTION
**Pull request by Truxnell**
# Pull Request

## What? (description)
Adding information on setting up forwarding talos logs to vector, along with a suggested config for on-forwarding to a Grafana Loki instance

## Why? (reasoning)

Give users a suggested path forward on another excellent logging solution to ease their setup & usage with talos.

## Acceptance

Please use the following checklist:

- [X] you linked an issue (if applicable)
- [X] you included tests (if applicable)
- [X] you ran conformance (`make conformance`)
- [X] you formatted your code (`make fmt`)
- [X] you linted your code (`make lint`)
- [X] you generated documentation (`make docs`)
- [X] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5591)

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
LGTM, would you mind adding the same to the 1.0 docs too?

**Comment by Truxnell** [comment]
@frezbo Done.  Wasn't sure how far back to go!

**Review by smira — APPROVED** [review]

**Review by frezbo — APPROVED** [review]

**Pull request merged**
