### PR TITLE
feat: add dm-cache dm-cache-smq kernel modules

### PR DESCRIPTION
**Pull request by chifu1234**
# Pull Request

https://github.com/siderolabs/pkgs/pull/1075

## Acceptance

Please use the following checklist:

- [x] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [x] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [x] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by chifu1234** [comment]
@smira  sorry don't really know talos source. Is this sufficient enough ?

**Comment by smira** [comment]
> @smira sorry don't really know talos source. Is this sufficient enough ? Do you normally add testing for kernel modules?

yes, thank you, I'll take it further

**Comment by chifu1234** [comment]
thanks for your quick reaction @smira !

**Comment by smira** [comment]
As this PR comes from a GitHub org, I can't push back updates, so I will re-create this PR.

**Pull request closed without merging**
