### PR TITLE
Adding Tremor Video

### PR DESCRIPTION
**Pull request by killcity**
# Pull Request

## What? 
Adding Tremor Video to the list of adopters.

## Why?
Supporting the project.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

Signed-off-by: BJ Badyk bbadyk@tremorvideo.com

### CODE REVIEW

**Comment by smira** [comment]
@killcity I can fix up the rest, but I need your DCO on the commit: https://wiki.linuxfoundation.org/dco

`git commit --amend -s` does this in the CLI, but if not CLI just put this line here, and I will add it back to the commit.

**Comment by killcity** [comment]
> @killcity I can fix up the rest, but I need your DCO on the commit: https://wiki.linuxfoundation.org/dco
> 
> `git commit --amend -s` does this in the CLI, but if not CLI just put this line here, and I will add it back to the commit.

@smira DCO added to commit. Does that work?

**Comment by smira** [comment]
> > @killcity I can fix up the rest, but I need your DCO on the commit: https://wiki.linuxfoundation.org/dco
> > `git commit --amend -s` does this in the CLI, but if not CLI just put this line here, and I will add it back to the commit.
> 
> @smira DCO added to commit. Does that work?

I don't see any DCO in your commit, in fact it's the same commit, probably forgot to push it?

**Comment by smira** [comment]
> > > @killcity I can fix up the rest, but I need your DCO on the commit: https://wiki.linuxfoundation.org/dco
> > > `git commit --amend -s` does this in the CLI, but if not CLI just put this line here, and I will add it back to the commit.
> > 
> > 
> > @smira DCO added to commit. Does that work?
> 
> I don't see any DCO in your commit, in fact it's the same commit, probably forgot to push it?

I see it in the PR description, I will fix it up

**Comment by killcity** [comment]
> > > > @killcity I can fix up the rest, but I need your DCO on the commit: https://wiki.linuxfoundation.org/dco
> > > > `git commit --amend -s` does this in the CLI, but if not CLI just put this line here, and I will add it back to the commit.
> > > 
> > > 
> > > @smira DCO added to commit. Does that work?
> > 
> > 
> > I don't see any DCO in your commit, in fact it's the same commit, probably forgot to push it?
> 
> I see it in the PR description, I will fix it up

Thanks!

**Review by smira — APPROVED** [review]

**Pull request merged**
