### PR TITLE
docs: code block copying

### PR DESCRIPTION
**Pull request by frezbo**
Enable code blocks copying

Ref: https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/

Supersedes #5235

Signed-off-by: Noel Georgi <git@frezbo.dev>

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5238)

### CODE REVIEW

**Review by Unix4ever — APPROVED** [review]

**Comment by frezbo** [comment]
image

Updated css to show the content type too

**Comment by smira** [comment]
should we also enable syntax highlighting and pull fixes from #5236 ?

**Comment by andrewrynhard** [comment]
> should we also enable syntax highlighting and pull fixes from #5236 ?

Good question. If this is already a feature of the theme then we should use that instead of maintaining out own IMHO. We just got out of that mess 😄.

**Comment by frezbo** [comment]
We already have syntax highlighting from whatever hugo uses

**Review by rsmitty — APPROVED** [review]

**Review by smira — APPROVED** [review]

**Pull request merged**
