### PR TITLE
chore: better lvm2 tests

### PR DESCRIPTION
**Pull request by frezbo**
Use LVM2 tests that relies on module loading by lvm.

Fixes: #9300

### CODE REVIEW

**Comment by smira** [comment]
why do we have gitbook here?

**Comment by frezbo** [comment]
> why do we have gitbook here?

I've no idea

**Comment by smira** [comment]
we should pull back in [`ec32f44` (#9348)](https://github.com/siderolabs/talos/pull/9348/commits/ec32f44c31ef2f3750a62b3fc39ac0a7ae01bde5)

**Review by smira — APPROVED** [review]

**Pull request merged**
