### PR TITLE
style: use correct capitalization for openstack

### PR DESCRIPTION
**Pull request by MindTooth**
# Pull Request

## What? (description)

Change references for OpenStack to the correct capitalization.

_**Need to setup a working Linux VM for running tests.  macOS did not work the best.  Hence draft status.**_

## Why? (reasoning)

Been working more with Talos on OpenStack as of recently and having the name wrong is a bit annoying.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by MindTooth** [comment]
Still compiles fine and is bootable on OpenStack.

Screenshot 2024-04-29 at 00 35 43

```
$ talosctl --talosconfig talosconfig version
Client:
	Tag:         v1.7.0
	SHA:         70fb41ff
	Built:       
	Go version:  go1.22.2
	OS/Arch:     darwin/arm64
Server:
	NODE:        control-plane-1
	Tag:         v1.7.0-alpha.1-92-g33e1a7622-dirty
	SHA:         33e1a762-dirty
	Built:       
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```

**Review by smira — APPROVED** [review]
:+1:

**Pull request merged**
