### PR TITLE
feat: send `actor id` to the SideroLink events sink

### PR DESCRIPTION
**Pull request by Unix4ever**
This might come handy to distinguish sequences, tasks initiated by a particular API request.

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
This is not backported properly - missing `git cherry-pick -x` flag

**Comment by smira** [comment]
(I will backport the original PR anyways, it's in the backports queue)

**Comment by Unix4ever** [comment]
should I close this one?

**Comment by smira** [comment]
up to you, but I'd close it, as it's missing proper links

**Pull request closed without merging**
