### PR TITLE
feat: support multiple Docker cluster in talosctl cluster create

### PR DESCRIPTION
**Pull request by smira**
Dynamically map Kubernetes and Talos API ports to an available port on the host, so every cluster gets its own unique set of parts.

As part of the changes, refactor the provision library and interfaces, dropping old weird interfaces replacing with (hopefully) much more descriptive names.

Fixes https://github.com/siderolabs/talos/issues/8141

### CODE REVIEW

**Comment by smira** [comment]
forked from #8476 as conform is picky about branch names :disappointed:

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
