### PR TITLE
chore: allow custom registry to build installer/imager

### PR DESCRIPTION
**Pull request by aarnaud**
# Pull Request

## What? (description)

use registry and username inside Dockerfile to allow build with custom registry

## Why? (reasoning)

impossible to `make imager` with specific kernel built and pkgs version

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by smira — COMMENTED** [review]
this won't work this way, as REGISTRY and USERNAME are specified for output images, not input images

the `ghcr.io/siderolabs` prefix can be customized, but it should be some other way

**Comment by aarnaud** [comment]
Can we define a new variable ? like `INPUT_REGISTRY` do we need to split the registry and username ? 

```
INPUT_REGISTRY=ghcr.io/siderolabs
```

**Comment by smira** [comment]
> Can we define a new variable ? like `INPUT_REGISTRY` do we need to split the registry and username ?
> 
> ```
> INPUT_REGISTRY=ghcr.io/siderolabs
> ```

I would probably call this `PKGS_PREFIX` specifically, so a package will be something like `${PKGS_PREFIX}/kernel:${PKGS}`

**Pull request merged**
