### PR TITLE
feat: add OpenNebula context support

### PR DESCRIPTION
**Pull request by shurkys**
# Pull Request

## What? (description)
add OpenNebula context support
## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by chrecht** [comment]
Hi,

I'm very glad you have implemented support for OpenNebula.
This is excellent work.

I did some tests and I could find a little issue if you use multiple network interfaces and ip address assignment from opennebula. In case you do not add a gateway the provisioning fails.

Do you mind to add a check if the variable ETHX_GATEWAY is not set then do not add a route.

thank you,
 Christian

**Comment by shurkys** [comment]
Hello!
Sorry for not replying for so long.
That's a good point, I see it's already taken care of, thanks!

**Pull request merged**
