### PR TITLE
test: fix assertion on reboot test

### PR DESCRIPTION
**Pull request by utkuozdemir**
Fix the reboot test assertion after the changed formatting.

Signed-off-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>

### CODE REVIEW

**Review by smira — APPROVED** [review]
let's first promote this to `integration-qemu` before merging it.

**Comment by utkuozdemir** [comment]
> let's first promote this to `integration-qemu` before merging it.

Yes, seems I promoted to the wrong one on the previous PR hence didn't catch it: https://github.com/siderolabs/talos/pull/6488#issuecomment-1310904483

**Pull request merged**
