### PR TITLE
feat: gather plaform dns names

### PR DESCRIPTION
**Pull request by sergelogvinov**
Retrieve the DNS names of instances from the platform metadata.

# Pull Request

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
@sergelogvinov looks like unit-tests are failing:

```
--- FAIL: TestParseMetadata (0.00s)
    --- FAIL: TestParseMetadata/V1 (0.00s)
        nocloud_test.go:103: 
```

**Comment by smira** [comment]
@sergelogvinov `make docs generate` missing: https://ci.dev.talos-systems.io/siderolabs/talos/43146/1/7

**Comment by sergelogvinov** [comment]
Sorry for that.... fully forgot about this command.... )

**Pull request merged**
