### PR TITLE
feat: add ctest package and base for test suite

### PR DESCRIPTION
**Pull request by DmitriyMV**
This change adds ctest package which adds DefaultSuite and helper functions.

Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5744)

### CODE REVIEW

**Review by Unix4ever — APPROVED** [review]
:cool: Would be great to have it somewhere in the separate module to use it in Arges :)

**Review by utkuozdemir — APPROVED** [review]
LGTM

**Comment by DmitriyMV** [comment]
@Unix4ever 

> Would be great to have it somewhere in the separate module to use it in Arges

The problem is that it uses `logging.Wrap` which is provided by `github.com/talos-systems/talos/pkg/logging`. Extracting the logging package seems unnecessary. Providing the callback to create logging instance will force us to use that callback everywhere. We could use `generic type factory` trick we use for Resources but I don't know if its a good idea to continue our abuse of generics.

**Pull request merged**
