### PR TITLE
fix: handle correctly change of listen address for maintenance service

### LINKED ISSUE #7738: Kernel log sender gets stuck when the connection is aborted

### PR DESCRIPTION
**Pull request by smira**
Fixes #7738

If the SideroLink address changes, maintenance service should listen on new address. Previously it worked "sometimes", as there was a race on maintenance config either be removed/recreated or just updated. In case of an update the listen address was not updated properly, but recreate case worked correctly.

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
maybe a test too?

**Comment by smira** [comment]
> maybe a test too?

it'd be hard, as the test listens on localhost... but probably I could try listening on a different port :thinking:

**Review by Unix4ever — APPROVED** [review]

**Comment by smira** [comment]
> > maybe a test too?
> 
> it'd be hard, as the test listens on localhost... but probably I could try listening on a different port 🤔

added a test with a change of port

**Pull request merged**
