### PR TITLE
docs: add kubevirt install

### PR DESCRIPTION
**Pull request by rothgar**
rebase of PR #9522

@MichaelTrip

# Pull Request

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by Darkfella91** [comment]
Hey, i've been toying with KubeVirt on Talos for a few days and the documentation on how to install it on talos is spot on. Could it be possible to also add information on how to setup pci device passthrough ? I've tried setting up udev rules to unbind the devices and then bind them to vfio_pci driver , but with no luck and there's zero information on how to set that up on Talos and im banging my head against the wall :) . Could be nice if you guys have managed to configure host devices passthrough to include it in the docs .

**Comment by MichaelTrip** [comment]
> Hey, i've been toying with KubeVirt on Talos for a few days and the documentation on how to install it on talos is spot on. Could it be possible to also add information on how to setup pci device passthrough ? I've tried setting up udev rules to unbind the devices and then bind them to vfio_pci driver , but with no luck and there's zero information on how to set that up on Talos and im banging my head against the wall :) . Could be nice if you guys have managed to configure host devices passthrough to include it in the docs . 

I will try to investigate this and add it to the docs if I find the time later in december. If you find a solution, don't hesitate to file a PR with your solution. 

Open source is all about sharing your knowledge ❤️

**Comment by Darkfella91** [comment]
Not sure how to automate that so it happens when talos boots

**Comment by MichaelTrip** [comment]
> Not sure how to automate that so it happens when talos boots

You could create an extension for that. Talos has a very nice extension feature that you could use for that. Or maybe a static pod in a DaemonSet or something?

**Comment by Darkfella91** [comment]
Tried running a DaemonSet that would unbind the original driver and bind to vfio but it breakes the zfs kernel module, because the device im unbinding is a sas card with 6 disks attached to it in a zpool. Talos kernel throws errors about i/o errors on that pool since it was already imported by the extension. After that creating or mounting PVCs on my other zfs pool that is used by openebs-zfs-localpv stops working for some reason. I need to figure out a cleaner method .

**Comment by Darkfella91** [comment]
Ok just had to export my zpool first then unbind and bind the sas card and no issues now :P

**Review by smira — APPROVED** [review]

**Pull request merged**
