### PR TITLE
feat: optionally decode hcloud userdata as base64 when fetching machine configuration

### PR DESCRIPTION
**Pull request by axiphi**
# Pull Request

## What? (description)

When fetching the machine configuration in the hcloud platform implementation, try to decode the data returned from the 'userdata' endpoint as a base64 string. If the data is not in base64 format, decoding does not succeed and the unmodified data is used (the previous behavior).
By allowing this base64 based input method, users can provide binary data instead of just UTF-8 as the machine configuration input and therefore make use of the built in Gzip compression mechanism. 

## Why? (reasoning)

The userdata that can be provided when creating a hcloud server is limited to 32kB.
When the machine configuration is provided in plain text format, this limit can be reached quickly, especially when using inline manifests. 

[This issue](https://github.com/siderolabs/talos/issues/8805) is caused by this limitation, though this PR provides a different solution from what is suggested in the issue.
(This PR tries to decode the userdata as base64 string directly instead of using the cloud-init mechanism.)

## Acceptance

- [X] you linked an issue (if applicable)
- [X] you included tests (if applicable)
- [X] you ran conformance (`make conformance`)
- [X] you formatted your code (`make fmt`)
- [X] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [X] you ran unit-tests (`make unit-tests`)

### CODE REVIEW

**Comment by smira** [comment]
Sorry, I don't think I understand this - base64 data is bigger than plain text, so how does it help?

**Comment by axiphi** [comment]
Sorry, could have been more clear about this initially: With the base64-based input method, users can provide binary data instead of just UTF-8 as the machine configuration input and therefore make use of the built in Gzip compression mechanism. This is the part where the data actually becomes smaller.

**Comment by sergelogvinov** [comment]
It make sense for all platforms.. Most of them have size limitations...

Thanks.

**Review by smira — APPROVED** [review]
I did some changes, thank you for your PR!

**Comment by axiphi** [comment]
> It make sense for all platforms.. Most of them have size limitations...
> 
> Thanks.

Hey @sergelogvinov,
sorry for the very late reply, I didn't see your message.
The reason I put the base64 decoding step into the hcloud-specific module instead of the generic initialization code is that other platforms already have built-in support for base64-encoded user-data at the platform level (e.g. see [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html)).

I guess you could make an argument that Talos could support this generically for all platforms anyway though.

**Pull request merged**
