### PR TITLE
docs: note that kernel cmdline params are only applied on upgrade

### PR DESCRIPTION
**Pull request by flokli**
See https://github.com/siderolabs/talos/issues/4880#issuecomment-1170965112

# Pull Request

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5845)

### CODE REVIEW

**Review by smira — APPROVED** [review]
thank you!

**Comment by frezbo** [comment]
fixing up docs for 1.0 also

**Comment by frezbo** [comment]
fixed up the working, let me know if it makes sense

**Review by smira — APPROVED** [review]

**Pull request merged**
