### PR TITLE
feat: provide platform network config for 'metal' in META

### PR DESCRIPTION
**Pull request by smira**
A special META key might contain optional platform network config for the `METAL` platform.

It is completely optional, but if present, it works same way as in the clouds: it is applied with low priority (can be overriden with machine config), but provides some initial defaults for the machine.

### CODE REVIEW

**Comment by smira** [comment]
Sample:

```
$ talosctl -n 172.20.0.3 meta write 0xa '{"externalIPs": ["1.2.3.4"]}'  
$ talosctl -n 172.20.0.3 get addresses external/1.2.3.4/32
NODE         NAMESPACE   TYPE            ID                    VERSION   ADDRESS      LINK
172.20.0.3   network     AddressStatus   external/1.2.3.4/32   1         1.2.3.4/32   external
$ talosctl -n 172.20.0.3 meta delete 0xa
$ talosctl -n 172.20.0.3 get addresses external/1.2.3.4/32
NODE   NAMESPACE   TYPE   ID   VERSION   ADDRESS   LINK
1 error occurred:
	* rpc error: code = NotFound desc = resource AddressStatuses.net.talos.dev(network/external/1.2.3.4/32@undefined) doesn't exist
```

**Review by frezbo — APPROVED** [review]

**Comment by frezbo** [comment]
> Sample:
> 
> ```
> $ talosctl -n 172.20.0.3 meta write 0xa '{"externalIPs": ["1.2.3.4"]}'  
> $ talosctl -n 172.20.0.3 get addresses external/1.2.3.4/32
> NODE         NAMESPACE   TYPE            ID                    VERSION   ADDRESS      LINK
> 172.20.0.3   network     AddressStatus   external/1.2.3.4/32   1         1.2.3.4/32   external
> $ talosctl -n 172.20.0.3 meta delete 0xa
> $ talosctl -n 172.20.0.3 get addresses external/1.2.3.4/32
> NODE   NAMESPACE   TYPE   ID   VERSION   ADDRESS   LINK
> 1 error occurred:
> 	* rpc error: code = NotFound desc = resource AddressStatuses.net.talos.dev(network/external/1.2.3.4/32@undefined) doesn't exist
> ```

I can already speculate users abusing this to add new network info :joy:

**Review by utkuozdemir — APPROVED** [review]
LGTM

**Pull request merged**
