### PR TITLE
chore: update kernel to the version with BTF support

### PR DESCRIPTION
**Pull request by smira**
See https://github.com/siderolabs/pkgs/pull/482

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Comment by smira** [comment]
This seems to work:

```shell
$ talosctl -n 172.20.0.2 cat /sys/kernel/btf/vmlinux > btf
$ bpftool btf dump file btf | head -20                                                                                                Чт 11 авг 2022 15:26:54
[1] INT 'long unsigned int' size=8 bits_offset=0 nr_bits=64 encoding=(none)
[2] CONST '(anon)' type_id=1
[3] PTR '(anon)' type_id=5
[4] INT 'char' size=1 bits_offset=0 nr_bits=8 encoding=(none)
[5] CONST '(anon)' type_id=4
[6] INT 'unsigned int' size=4 bits_offset=0 nr_bits=32 encoding=(none)
[7] CONST '(anon)' type_id=6
[8] INT 'signed char' size=1 bits_offset=0 nr_bits=8 encoding=(none)
[9] TYPEDEF '__u8' type_id=10
[10] INT 'unsigned char' size=1 bits_offset=0 nr_bits=8 encoding=(none)
[11] CONST '(anon)' type_id=10
[12] TYPEDEF '__s16' type_id=13
[13] INT 'short int' size=2 bits_offset=0 nr_bits=16 encoding=SIGNED
[14] TYPEDEF '__u16' type_id=15
[15] INT 'short unsigned int' size=2 bits_offset=0 nr_bits=16 encoding=(none)
[16] TYPEDEF '__s32' type_id=17
[17] INT 'int' size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[18] TYPEDEF '__u32' type_id=6
[19] TYPEDEF '__s64' type_id=20
[20] INT 'long long int' size=8 bits_offset=0 nr_bits=64 encoding=SIGNED
```

**Comment by smira** [comment]
more on this: https://facebookmicrosites.github.io/bpf/blog/2020/02/19/bpf-portability-and-co-re.html

and it actually seems to work:

```shell
$ bpftool btf dump file btf format c > vmlinux.h
```

```c
struct file_system_type {
        const char *name;
        int fs_flags;
        int (*init_fs_context)(struct fs_context *);
        const struct fs_parameter_spec *parameters;
        struct dentry * (*mount)(struct file_system_type *, int, const char *, void *);
        void (*kill_sb)(struct super_block *);
        struct module *owner;
        struct file_system_type *next;
        struct hlist_head fs_supers;
        struct lock_class_key s_lock_key;
        struct lock_class_key s_umount_key;
        struct lock_class_key s_vfs_rename_key;
        struct lock_class_key s_writers_key[3];
        struct lock_class_key i_lock_key;
        struct lock_class_key i_mutex_key;
        struct lock_class_key invalidate_lock_key;
        struct lock_class_key i_mutex_dir_key;
};

struct qspinlock {
        union {
                atomic_t val;
                struct {
                        u8 locked;
                        u8 pending;
                };
                struct {
                        u16 locked_pending;
                        u16 tail;
                };
        };
};
```

**Review by frezbo — APPROVED** [review]
:cool: , I'm excited for the day when we can run bpf programs like how [inspektor-gadget](https://github.com/kinvolk/inspektor-gadget) does, but without k8s

**Pull request merged**
