### PR TITLE
chore: update dependencies

### LINKED ISSUE #7859: VIP access during cluster upgrade
## Bug Report

K8s upgrade fails due to failing vip access.

### Description

During k8s version upgrade, the VIP access will fail when the node that currently holds the vip is upgrading.
The apiserver actually upgrades correctly but the upgrade command fail on network error.

Relaunching the upgrade command will continue the upgrade further (as the apiserver did upgrade correctly) but then will fail again when upgrading the kubelet of the node holding the VIP. 

Talos should probably move the vip before trying to upgrade the components on the node, or wait a bit for the vip to move instead of failing immediatly.

Notes:
- Control plane nodes IP are `192.168.70.101`, `192.168.70.102`, `192.168.70.103`
- Configured VIP is `192.168.70.10`

talos endpoints configuration in `.talos/config`
```
    talos-cluster:
        endpoints:
            - 192.168.70.101
            - 192.168.70.102
            - 192.168.70.103
```

kubeconfig: endpoint:
```
server: https://192.168.70.10:6443
```

### Logs

First upgrade attempt:

```
talosctl --nodes 192.168.70.101 upgrade-k8s --to 1.27.6
automatically detected the lowest Kubernetes version 1.26.9
discovered controlplane nodes ["192.168.70.103" "192.168.70.101" "192.168.70.102"]
discovered worker nodes ["192.168.70.201" "192.168.70.202"]
checking for removed Kubernetes component flags
checking for removed Kubernetes API resource versions
 > "192.168.70.103": pre-pulling registry.k8s.io/kube-apiserver:v1.27.6
 > "192.168.70.101": pre-pulling registry.k8s.io/kube-apiserver:v1.27.6
 > "192.168.70.102": pre-pulling registry.k8s.io/kube-apiserver:v1.27.6
 > "192.168.70.103": pre-pulling registry.k8s.io/kube-controller-manager:v1.27.6
 > "192.168.70.101": pre-pulling registry.k8s.io/kube-controller-manager:v1.27.6
 > "192.168.70.102": pre-pulling registry.k8s.io/kube-controller-manager:v1.27.6
 > "192.168.70.103": pre-pulling registry.k8s.io/kube-scheduler:v1.27.6
 > "192.168.70.101": pre-pulling registry.k8s.io/kube-scheduler:v1.27.6
 > "192.168.70.102": pre-pulling registry.k8s.io/kube-scheduler:v1.27.6
 > "192.168.70.103": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
 > "192.168.70.101": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
 > "192.168.70.102": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
 > "192.168.70.201": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
 > "192.168.70.202": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
updating "kube-apiserver" to version "1.27.6"
 > "192.168.70.103": starting update
 > update kube-apiserver: v1.26.9 -> 1.27.6
 > "192.168.70.103": machine configuration patched
 > "192.168.70.103": waiting for kube-apiserver pod update
 < "192.168.70.103": successfully updated
 > "192.168.70.101": starting update
 > update kube-apiserver: v1.26.9 -> 1.27.6
 > "192.168.70.101": machine configuration patched
 > "192.168.70.101": waiting for kube-apiserver pod update
failed updating service "kube-apiserver": error updating node "192.168.70.101": 2 error(s) occurred:
        config version mismatch: got "1", expected "2"
        Get "https://192.168.70.10:6443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app+%3D+kube-apiserver": dial tcp 192.168.70.10:6443: connectex: No connection could be made because the target machine actively refused it.
```

Second attempt:

```
talosctl --nodes 192.168.70.101 upgrade-k8s --to 1.27.6
automatically detected the lowest Kubernetes version 1.26.9
discovered controlplane nodes ["192.168.70.103" "192.168.70.101" "192.168.70.102"]
discovered worker nodes ["192.168.70.201" "192.168.70.202"]
checking for removed Kubernetes component flags
checking for removed Kubernetes API resource versions
 > "192.168.70.103": pre-pulling registry.k8s.io/kube-apiserver:v1.27.6
 > "192.168.70.101": pre-pulling registry.k8s.io/kube-apiserver:v1.27.6
 > "192.168.70.102": pre-pulling registry.k8s.io/kube-apiserver:v1.27.6
 > "192.168.70.103": pre-pulling registry.k8s.io/kube-controller-manager:v1.27.6
 > "192.168.70.101": pre-pulling registry.k8s.io/kube-controller-manager:v1.27.6
 > "192.168.70.102": pre-pulling registry.k8s.io/kube-controller-manager:v1.27.6
 > "192.168.70.103": pre-pulling registry.k8s.io/kube-scheduler:v1.27.6
 > "192.168.70.101": pre-pulling registry.k8s.io/kube-scheduler:v1.27.6
 > "192.168.70.102": pre-pulling registry.k8s.io/kube-scheduler:v1.27.6
 > "192.168.70.103": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
 > "192.168.70.101": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
 > "192.168.70.102": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
 > "192.168.70.201": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
 > "192.168.70.202": pre-pulling ghcr.io/siderolabs/kubelet:v1.27.6
updating "kube-apiserver" to version "1.27.6"
 > "192.168.70.103": starting update
 > "192.168.70.103": machine configuration patched
 > "192.168.70.103": waiting for kube-apiserver pod update
 < "192.168.70.103": successfully updated
 > "192.168.70.101": starting update
 > "192.168.70.101": machine configuration patched
 > "192.168.70.101": waiting for kube-apiserver pod update
 < "192.168.70.101": successfully updated
 > "192.168.70.102": starting update
 > update kube-apiserver: v1.26.9 -> 1.27.6
 > "192.168.70.102": machine configuration patched
 > "192.168.70.102": waiting for kube-apiserver pod update
 < "192.168.70.102": successfully updated
updating "kube-controller-manager" to version "1.27.6"
 > "192.168.70.103": starting update
 > update kube-controller-manager: v1.26.9 -> 1.27.6
 > "192.168.70.103": machine configuration patched
 > "192.168.70.103": waiting for kube-controller-manager pod update
 < "192.168.70.103": successfully updated
 > "192.168.70.101": starting update
 > update kube-controller-manager: v1.26.9 -> 1.27.6
 > "192.168.70.101": machine configuration patched
 > "192.168.70.101": waiting for kube-controller-manager pod update
 < "192.168.70.101": successfully updated
 > "192.168.70.102": starting update
 > update kube-controller-manager: v1.26.9 -> 1.27.6
 > "192.168.70.102": machine configuration patched
 > "192.168.70.102": waiting for kube-controller-manager pod update
 < "192.168.70.102": successfully updated
updating "kube-scheduler" to version "1.27.6"
 > "192.168.70.103": starting update
 > update kube-scheduler: v1.26.9 -> 1.27.6
 > "192.168.70.103": machine configuration patched
 > "192.168.70.103": waiting for kube-scheduler pod update
 < "192.168.70.103": successfully updated
 > "192.168.70.101": starting update
 > update kube-scheduler: v1.26.9 -> 1.27.6
 > "192.168.70.101": machine configuration patched
 > "192.168.70.101": waiting for kube-scheduler pod update
 < "192.168.70.101": successfully updated
 > "192.168.70.102": starting update
 > update kube-scheduler: v1.26.9 -> 1.27.6
 > "192.168.70.102": machine configuration patched
 > "192.168.70.102": waiting for kube-scheduler pod update
 < "192.168.70.102": successfully updated
updating kube-proxy to version "1.27.6"
 > "192.168.70.103": starting update
 > "192.168.70.101": starting update
 > "192.168.70.102": starting update
updating kubelet to version "1.27.6"
 > "192.168.70.103": starting update
 > update kubelet: 1.26.9 -> 1.27.6
 > "192.168.70.103": machine configuration patched
 > "192.168.70.103": waiting for kubelet restart
 > "192.168.70.103": waiting for node update
 < "192.168.70.103": successfully updated
 > "192.168.70.101": starting update
 > update kubelet: 1.26.9 -> 1.27.6
 > "192.168.70.101": machine configuration patched
 > "192.168.70.101": waiting for kubelet restart
 > "192.168.70.101": waiting for node update
failed upgrading kubelet: error updating node "192.168.70.101": 1 error(s) occurred:
        Get "https://192.168.70.10:6443/api/v1/nodes": read tcp 192.168.70.1:56646->192.168.70.10:6443: wsarecv: An existing connection was forcibly closed by the remote host.
```

### Environment

```talosctl version
Client:
        Tag:         v1.5.3
        SHA:         cb21c671
        Built:
        Go version:  go1.20.8
        OS/Arch:     windows/amd64
Server:
        NODE:        192.168.70.101
        Tag:         v1.5.3
        SHA:         cb21c671
        Built:
        Go version:  go1.20.8
        OS/Arch:     linux/amd64
        Enabled:     RBAC````

- Kubernetes version: [`kubectl version --short`]
````
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.26.9
````
- Platform:
Host: Windows 10 Pro
Talos running in VMs managed by hyper-v

### PR DESCRIPTION
**Pull request by smira**
Containerd 1.7.7, Linux 6.1.58.

Fixes #7859

### CODE REVIEW

**Comment by smira** [comment]
The biggest change is migrating to `cgroups/v3`.

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
